In [1]:
import pandas as pd
import numpy as np
import xml.etree.ElementTree as ET

In [2]:
tree = ET.parse('s3891013_dataset1.xml')
root = tree.getroot()

In [3]:
data = []

# Iterating through each source and its rows
for source in root.findall('Source'):
    sourceName = source.attrib['Name']
    for row in source.findall('Row'):
        record = {
            'Id': row.attrib['ID'],
            'Title': row.find('Title').text if row.find('Title') is not None else None,
            'Location': row.find('Location').text if row.find('Location') is not None else None,
            'Company': row.find('Company').text if row.find('Company') is not None else None,
            'ContractType': row.find('ContractType').text if row.find('ContractType') is not None else None, # Placeholder for future use if needed.
            'ContractTime': row.find('ContractTime').text if row.find('ContractTime') is not None else None,
            'Category': row.find('Category').text if row.find('Category') is not None else None,
            'Salary': row.find('Salary').text if row.find('Salary') is not None else None,
            'OpenDate': row.find('OpenDate').text if row.find('OpenDate') is not None else None,
            'CloseDate': row.find('CloseDate').text if row.find('CloseDate') is not None else None,
            'SourceName': sourceName
        }
        data.append(record)

df = pd.DataFrame(data)

In [4]:
df.head(10)

,Id,Title,Location,Company,ContractType,ContractTime,Category,Salary,OpenDate,CloseDate,SourceName
0,68241654,PI Underwriter Regional Markets,London,Idex Consulting LLP,None,permanent,Accounting & Finance Jobs,57500,20121214T000000,20130212T000000,insurancejobs.co.uk
1,71138818,COMMERCIAL INSURANCE ACCOUNT HANDLER HERTFORD...,London,Clark James Insurance And Financial Services R...,None,permanent,Accounting & Finance Jobs,26000,20130314T150000,20130612T150000,insurancejobs.co.uk
2,71391843,Claims Handler Motor Trade,Hertfordshire,Lawes Insurance Recruitment,None,permanent,Accounting & Finance Jobs,19000,20131124T120000,20140222T120000,insurancejobs.co.uk
3,70420154,Commercial Jewellers Block Account Handler,Birmingham,Lawes Insurance Recruitment,None,permanent,Accounting & Finance Jobs,22000,20121230T150000,20130129T150000,insurancejobs.co.uk
4,67779524,Protection Indemnity Underwriter,The City,Lawes Insurance Recruitment,None,permanent,Accounting & Finance Jobs,45000,20120904T150000,20121103T150000,insurancejobs.co.uk
5,70420179,Underwriting Manager Transportation/fleet,Shropshire,Lawes Insurance Recruitment,None,permanent,Accounting & Finance Jobs,45000,20130104T150000,20130404T150000,insurancejobs.co.uk
6,70420168,Insurance Risk Control/Senior Surveyor,London,Lawes Insurance Recruitment,None,permanent,Accounting & Finance Jobs,45000,20120329T150000,20120627T150000,insurancejobs.co.uk
7,72218671,Personal Lines Sales Executive,Bracknell,MW Appointments,None,permanent,Accounting & Finance Jobs,19000,20130614T120000,20130714T120000,insurancejobs.co.uk
8,68621337,Commercial Account Executive (Manchester) ***...,Manchester,Idex Consulting LLP,None,permanent,Accounting & Finance Jobs,45000,20130214T000000,20130316T000000,insurancejobs.co.uk
9,67779521,Senior Commercial Business Development Manager,Lancashire,Lawes Insurance Recruitment,None,permanent,Accounting & Finance Jobs,50000,20130904T120000,20131203T120000,insurancejobs.co.uk